method: onet
data:
  input_type: voxels
  path: data/ShapeNet
  dim: 3
  points_subsample: 1024
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: voxel_simple
  c_dim: 256 
  z_dim: 0
training:
  out_dir:  out/voxels/onet
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  resolution_0: 32
  upsampling_steps: 3
  # refinement_step: 0
  # use_sampling: false
  simplify_nfaces: 50000
  batch_size: 250000
  refine: false
  n_x: 128
  n_z: 1
  normals: false
